### ISSUE TITLE
setting the maxResults on the KeyVaultConfigService causes the retrival of the secrets to fail

### ISSUE THREAD

**Issue by rfrappier** [julienblin/uno-serverless#73]
setting maxResults, see below, will later fail when trying to retrieve a config parameter

new KeyVaultConfigService({
        keyVaultUrl: process.env.KEYVAULT!,
        maxResults: 40,
      });

**Comment by julienblin** [comment]
maxResults > 25 triggers an Error in the Azure KeyVaultClient class:

```javascript
UnhandledPromiseRejectionWarning: Error: "maxresults" should satisfy the constraint - "InclusiveMaximum": 25
    at KeyVaultClient._getSecrets (/Users/julien/dev/uno-serverless/packages/uno-serverless-azure/node_modules/azure-keyvault/lib/keyVaultClient.js:4214:15)
    at Promise (/Users/julien/dev/uno-serverless/packages/uno-serverless-azure/node_modules/azure-keyvault/lib/keyVaultClient.js:18388:14)
    at new Promise (<anonymous>)
    at KeyVaultClient.getSecrets (/Users/julien/dev/uno-serverless/packages/uno-serverless-azure/node_modules/azure-keyvault/lib/keyVaultClient.js:18387:14)
    at KeyVaultConfigService.getParameters (/Users/julien/dev/uno-serverless/packages/uno-serverless-azure/src/services/config.ts:88:24)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

However, the class needs to be fixed to properly handle nextLinks.
